HPRC_Fortran: HPRC_Fortran.tex  
	pdflatex HPRC_Fortran
	pdflatex HPRC_Fortran
	evince HPRC_Fortran.pdf
clean:
	@rm -f  *.dvi *.aux *.log *.lot *.lof *.bbl *.blg *.out *.toc *.backup *.vrb *.snm *.nav *~
